# yaml-language-server: $schema=https://raw.githubusercontent.com/Kometa-Team/Kometa/nightly/json-schema/config-schema.json

############################################
# ######################################## #
# #  _  _____  __  __ _____ _____  _     # #
# # | |/ / _ \|  \/  | ____|_   _|/ \    # #
# # | ' / | | | |\/| |  _|   | | / _ \   # #
# # | . \ |_| | |  | | |___  | |/ ___ \  # #
# # |_|\_\___/|_|  |_|_____| |_/_/   \_\ # #
# #                                      # #
############################################

#==================== whe_wth_test1 ====================#
# whe_wth_test1 config created by Quickstart on 2025-06-29 18:29:32
# Connected to server Plexypus version 1.41.9.9912-371133ff9
# Running on Linux version 22.04.5 LTS (Jammy Jellyfish)
# Plex DB cache setting: 1024 MB
# PlexPass: True on Public update channel.
# Scheduled maintenance running between 2:00 and 5:00
# Quickstart version: 0.8.6-build22 | Branch: develop | Environment: Docker
###
# Libraries configured with Quickstart: 1 movie, 1 show
# Information on library: Movies
# Type: Movie
# Agent: tv.plex.agents.movie
# Scanner: Plex Movie
# Ratings Source: IMDb
# 
# Information on library: TV Shows
# Type: Show
# Agent: tv.plex.agents.series
# Scanner: Plex TV Series
# Ratings Source: N/A
### 
# We highly recommend using Visual Studio Code with indent-rainbow by oderwat extension and YAML by Red Hat extension. Visual Studio Code will also leverage the above link (yaml-language-server) to enhance Kometa yml edits.
###

# This file is auto-generated by Quickstart. Do not edit manually unless you know what you are doing.
#==================== whe_wth_test1 ====================#


##############################################
#  _     _ _                    _            #
# | |   (_) |__  _ __ __ _ _ __(_) ___  ___  #
# | |   | | '_ \| '__/ _` | '__| |/ _ \/ __| #
# | |___| | |_) | | | (_| | |  | |  __/\__ \ #
# |_____|_|_.__/|_|  \__,_|_|  |_|\___||___/ #
#                                            #
##############################################
libraries:
###################################
#  __  __            _            #
# |  \/  | _____   _(_) ___  ___  #
# | |\/| |/ _ \ \ / / |/ _ \/ __| #
# | |  | | (_) \ V /| |  __/\__ \ #
# |_|  |_|\___/ \_/ |_|\___||___/ #
#                                 #
###################################
  Movies:
    template_variables:
      use_separator: false
####################################################
#   ____      _ _           _   _                  #
#  / ___|___ | | | ___  ___| |_(_) ___  _ __  ___  #
# | |   / _ \| | |/ _ \/ __| __| |/ _ \| '_ \/ __| #
# | |__| (_) | | |  __/ (__| |_| | (_) | | | \__ \ #
#  \____\___/|_|_|\___|\___|\__|_|\___/|_| |_|___/ #
#                                                  #
####################################################
    collection_files:
    - default: oscars
      template_variables:
        use_best_picture: true
        radarr_add_missing_best_picture: true
        use_best_director: false
        radarr_add_missing_best_director: false
        collection_mode: hide_items
        sort_by: release.desc
    - default: choice
      template_variables:
        use_best: false
        radarr_add_missing_best: true
        collection_mode: hide_items
        sort_by: release.desc
    - default: golden
      template_variables:
        use_best_picture: true
        radarr_add_missing_best_picture: true
        use_best_director: false
        radarr_add_missing_best_director: false
        collection_mode: default
        sort_by: release.desc
    - default: pca
      template_variables:
        use_pca: true
        radarr_add_missing_pca: true
        collection_mode: hide_items
        sort_by: release.desc
    - default: tautulli
      template_variables:
        use_popular: true
        radarr_add_missing_popular: true
        use_watched: true
        radarr_add_missing_watched: true
        style: color
        collection_mode: default
        sort_by: release.desc
    - default: imdb
      template_variables:
        use_top: true
        radarr_add_missing_top: true
        use_popular: true
        radarr_add_missing_popular: true
        use_lowest: false
        radarr_add_missing_lowest: false
        style: color
        collection_mode: default
        sort_by: release.desc
    - default: tmdb
      template_variables:
        use_airing: false
        radarr_add_missing_airing: false
        use_air: false
        radarr_add_missing_air: false
        use_popular: true
        radarr_add_missing_popular: true
        use_top: true
        radarr_add_missing_top: true
        use_trending: false
        radarr_add_missing_trending: false
        style: color
        collection_mode: default
        sort_by: release.desc
    - default: universe
      template_variables:
        use_avp: false
        radarr_add_missing_avp: false
        use_arrow: false
        radarr_add_missing_arrow: false
        use_dca: false
        radarr_add_missing_dca: false
        use_dcu: false
        radarr_add_missing_dcu: false
        use_fast: false
        radarr_add_missing_fast: false
        use_marvel: false
        radarr_add_missing_marvel: false
        use_mcu: true
        radarr_add_missing_mcu: true
        use_middle: true
        radarr_add_missing_middle: true
        use_rocky: false
        radarr_add_missing_rocky: false
        use_trek: true
        radarr_add_missing_trek: true
        use_star: true
        radarr_add_missing_star: true
        use_mummy: false
        radarr_add_missing_mummy: false
        use_askew: false
        radarr_add_missing_askew: false
        use_wizard: true
        radarr_add_missing_wizard: true
        use_xmen: false
        radarr_add_missing_xmen: false
        collection_mode: hide_items
        sort_by: release.desc
############################################
#   ___                 _                  #
#  / _ \__   _____ _ __| | __ _ _   _ ___  #
# | | | \ \ / / _ \ '__| |/ _` | | | / __| #
# | |_| |\ V /  __/ |  | | (_| | |_| \__ \ #
#  \___/  \_/ \___|_|  |_|\__,_|\__, |___/ #
#                               |___/      #
############################################
    overlay_files:
    - default: ribbon
      template_variables:
        style: yellow
###################################################
#  _______     __  ____  _                        #
# |_   _\ \   / / / ___|| |__   _____      _____  #
#   | |  \ \ / /  \___ \| '_ \ / _ \ \ /\ / / __| #
#   | |   \ V /    ___) | | | | (_) \ V  V /\__ \ #
#   |_|    \_/    |____/|_| |_|\___/ \_/\_/ |___/ #
#                                                 #
###################################################
  TV Shows:
    template_variables:
      use_separator: false
####################################################
#   ____      _ _           _   _                  #
#  / ___|___ | | | ___  ___| |_(_) ___  _ __  ___  #
# | |   / _ \| | |/ _ \/ __| __| |/ _ \| '_ \/ __| #
# | |__| (_) | | |  __/ (__| |_| | (_) | | | \__ \ #
#  \____\___/|_|_|\___|\___|\__|_|\___/|_| |_|___/ #
#                                                  #
####################################################
    collection_files:
    - default: choice
      template_variables:
        use_best: true
        sonarr_add_missing_best: true
        collection_mode: hide_items
        sort_by: release.desc
    - default: emmy
      template_variables:
        use_best: true
        sonarr_add_missing_best: true
        collection_mode: hide
        sort_by: release.desc
    - default: golden
      template_variables:
        use_best_picture: true
        sonarr_add_missing_best_picture: true
        use_best_director: false
        sonarr_add_missing_best_director: false
        collection_mode: hide_items
        sort_by: release.desc
    - default: pca
      template_variables:
        use_pca: true
        sonarr_add_missing_pca: true
        collection_mode: hide_items
        sort_by: release.desc
    - default: tautulli
      template_variables:
        use_popular: true
        sonarr_add_missing_popular: false
        use_watched: false
        sonarr_add_missing_watched: false
        style: color
        collection_mode: default
        sort_by: release.desc
    - default: imdb
      template_variables:
        use_top: true
        sonarr_add_missing_top: false
        use_popular: false
        sonarr_add_missing_popular: false
        use_lowest: false
        sonarr_add_missing_lowest: false
        style: color
        collection_mode: default
        sort_by: release.desc
    - default: franchise
      template_variables:
        collection_mode: hide_items
        sort_by: release.desc
    - default: universe
      template_variables:
        use_avp: false
        sonarr_add_missing_avp: false
        use_arrow: false
        sonarr_add_missing_arrow: false
        use_dca: false
        sonarr_add_missing_dca: false
        use_dcu: false
        sonarr_add_missing_dcu: false
        use_fast: false
        sonarr_add_missing_fast: false
        use_marvel: false
        sonarr_add_missing_marvel: false
        use_mcu: true
        sonarr_add_missing_mcu: true
        use_middle: true
        sonarr_add_missing_middle: true
        use_rocky: false
        sonarr_add_missing_rocky: false
        use_trek: true
        sonarr_add_missing_trek: false
        use_star: true
        sonarr_add_missing_star: false
        use_mummy: false
        sonarr_add_missing_mummy: false
        use_askew: false
        sonarr_add_missing_askew: false
        use_wizard: false
        sonarr_add_missing_wizard: false
        use_xmen: false
        sonarr_add_missing_xmen: false
        collection_mode: default
        sort_by: release.desc

#########################################
#  ____  _             _ _     _        #
# |  _ \| | __ _ _   _| (_)___| |_ ___  #
# | |_) | |/ _` | | | | | / __| __/ __| #
# |  __/| | (_| | |_| | | \__ \ |_\__ \ #
# |_|   |_|\__,_|\__, |_|_|___/\__|___/ #
#                |___/                  #
#########################################
playlist_files:
- default: playlist
  template_variables:
    libraries:
    - Movies
    - TV Shows

##########################################
#  ____       _   _   _                  #
# / ___|  ___| |_| |_(_)_ __   __ _ ___  #
# \___ \ / _ \ __| __| | '_ \ / _` / __| #
#  ___) |  __/ |_| |_| | | | | (_| \__ \ #
# |____/ \___|\__|\__|_|_| |_|\__, |___/ #
#                             |___/      #
##########################################
settings:
  asset_depth: 0
  asset_directory:
  - config/assets
  asset_folders: true
  cache: true
  cache_expiration: 60
  create_asset_folders: false
  custom_repo:
  default_collection_order: release.asc
  delete_below_minimum: true
  delete_not_scheduled: false
  dimensional_asset_rename: false
  download_url_assets: false
  ignore_ids:
  ignore_imdb_ids:
  item_refresh_delay: 0
  minimum_items: 1
  missing_only_released: false
  only_filter_missing: false
  overlay_artwork_filetype: webp_lossy
  overlay_artwork_quality: 90
  playlist_exclude_users:
  playlist_report: false
  playlist_sync_to_users:
  prioritize_assets: false
  run_again_delay: 2
  run_order:
  - operations
  - metadata
  - collections
  - overlays
  save_report: false
  show_asset_not_needed: true
  show_filtered: false
  show_missing: true
  show_missing_assets: true
  show_missing_episode_assets: false
  show_missing_season_assets: false
  show_options: true
  show_unconfigured: true
  show_unfiltered: false
  show_unmanaged: true
  sync_mode: append
  tvdb_language: eng
  verify_ssl: true

#######################
#  ____  _            #
# |  _ \| | _____  __ #
# | |_) | |/ _ \ \/ / #
# |  __/| |  __/>  <  #
# |_|   |_|\___/_/\_\ #
#                     #
#######################
plex:
  clean_bundles: true
  db_cache: 1024
  empty_trash: true
  optimize: true
  timeout: 60
  token: _F3VgHKzF6c61taqFuYH
  url: http://192.168.99.35:32400
  verify_ssl: true

##############################
#  _____ __  __ ____  _      #
# |_   _|  \/  |  _ \| |__   #
#   | | | |\/| | | | | '_ \  #
#   | | | |  | | |_| | |_) | #
#   |_| |_|  |_|____/|_.__/  #
#                            #
##############################
tmdb:
  apikey: 70c5bbc8137e617123cf8adc7fe086b9
  cache_expiration: 60
  language: en
  region: US

#####################################
#  _____           _         _ _ _  #
# |_   _|_ _ _   _| |_ _   _| | (_) #
#   | |/ _` | | | | __| | | | | | | #
#   | | (_| | |_| | |_| |_| | | | | #
#   |_|\__,_|\__,_|\__|\__,_|_|_|_| #
#                                   #
#####################################
tautulli:
  apikey: 2e4be55de3f349b98ca54cc5dc72a66e
  url: http://192.168.99.33:8181

###################################
#   ____ _ _   _   _       _      #
#  / ___(_) |_| | | |_   _| |__   #
# | |  _| | __| |_| | | | | '_ \  #
# | |_| | | |_|  _  | |_| | |_) | #
#  \____|_|\__|_| |_|\__,_|_.__/  #
#                                 #
###################################
github:
  token: 
    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

##############################
#   ___  __  __ ____  _      #
#  / _ \|  \/  |  _ \| |__   #
# | | | | |\/| | | | | '_ \  #
# | |_| | |  | | |_| | |_) | #
#  \___/|_|  |_|____/|_.__/  #
#                            #
##############################
omdb:
  apikey: 79c9c5d3
  cache_expiration: 60

########################################
#  __  __ ____  ____  _     _     _    #
# |  \/  |  _ \| __ )| |   (_)___| |_  #
# | |\/| | | | |  _ \| |   | / __| __| #
# | |  | | |_| | |_) | |___| \__ \ |_  #
# |_|  |_|____/|____/|_____|_|___/\__| #
#                                      #
########################################
mdblist:
  apikey: psymniazby56qouxfrpvj64ag
  cache_expiration: 60

#############################################
#  _   _       _   _  __ _                  #
# | \ | | ___ | |_(_)/ _(_) __ _ _ __ _ __  #
# |  \| |/ _ \| __| | |_| |/ _` | '__| '__| #
# | |\  | (_) | |_| |  _| | (_| | |  | |    #
# |_| \_|\___/ \__|_|_| |_|\__,_|_|  |_|    #
#                                           #
#############################################
notifiarr:
  apikey: 00c57743-9ba6-498b-a6af-ca94f878a232

######################################
#  ____           _                  #
# |  _ \ __ _  __| | __ _ _ __ _ __  #
# | |_) / _` |/ _` |/ _` | '__| '__| #
# |  _ < (_| | (_| | (_| | |  | |    #
# |_| \_\__,_|\__,_|\__,_|_|  |_|    #
#                                    #
######################################
radarr:
  add_existing: true
  add_missing: true
  availability: announced
  ignore_cache: false
  monitor: true
  monitor_existing: false
  plex_path:
  quality_profile: (Guide) Remux + WEB 1080p
  radarr_path:
  root_folder_path: /mnt/pve/Plex-Media/media/movies
  search: true
  tag:
  token: e984928b596a4b18947b4f078cd7fc49
  upgrade_existing: true
  url: http://192.168.99.223:7878

#######################################
#  ____                               #
# / ___|  ___  _ __   __ _ _ __ _ __  #
# \___ \ / _ \| '_ \ / _` | '__| '__| #
#  ___) | (_) | | | | (_| | |  | |    #
# |____/ \___/|_| |_|\__,_|_|  |_|    #
#                                     #
#######################################
sonarr:
  add_existing: true
  add_missing: true
  cutoff_search: false
  ignore_cache: false
  language_profile: English
  monitor: future
  monitor_existing: false
  plex_path:
  quality_profile: (Guide) WEB-1080p (Alternative)
  root_folder_path: /mnt/pve/Plex-Media/media/tv shows
  search: false
  season_folder: true
  series_type: standard
  sonarr_path:
  tag:
  token: fdd234bb5d8444febe41e974e8740966
  upgrade_existing: true
  url: http://192.168.99.224:8989
